source/source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('accounts/', include('accounts.urls')),
    path('projects/', include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/tasks/urls.py
from django.urls import path
from .views import HomeView, TaskListView, TaskDetailView, TaskUpdateView, TaskDeleteView, TaskCreateView, MyTaskList

urlpatterns = [
    path('', HomeView.as_view(), name='home_page'),
    path('list/', TaskListView.as_view(), name='task_list'),
    path('mylist/', MyTaskList.as_view(), name='my_task_list'),
    path('detail/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('update/<int:pk>/', TaskUpdateView.as_view(), name='task_update'),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name='task_delete'),
    path('create/', TaskCreateView.as_view(), name='create_task'),

]

source/projects/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.

class Projects(models.Model):
    name = models.CharField(max_length=250, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(get_user_model(), related_name='users', verbose_name='users')

    def __str__(self):
        return self.name

    def to_dict(self):
        return {
            'title': self.name,
            'description': self.description,
            'created_at': self.created_at.isoformat(),
        }

source/templates/partials/error_modal.html
 <!-- Модальное окно -->
<div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="errorModalLabel">Error</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="errorModalBody">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

source/templates/partials/error_page.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
  <div class="card-body">
    <h1>Error</h1>
      {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
  </div>
</div>
{% endblock %}

source/templates/partials/navigation.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home_page' %}">To_Do_List<img src="https://lh3.googleusercontent.com/lpOEDLcrHECiDtFaWRA8szt3-qhFilrqkuMBnUa8U5OoU2Jc8uKo1xnuaWK5v4kxV9E=w300" alt="" height="75"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home_page' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'task_list' %}">Task list</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'projects_list' %}">Projects list</a>
        </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'my_task_list' %}">My Task</a>
        </li>
            {% endif %}
      </ul>

    </div>
    <div class="d-flex">
    {% if not request.user.is_authenticated %}
    <a class="btn btn-outline-success btn-sm me-3" aria-current="page" href="{% url 'login' %}?next={{ request.get_full_path }}">Login</a>
    <a class="btn btn-outline-secondary btn-sm" aria-current="page" href="{% url 'register' %}?next={{ request.get_full_path }}">Register</a>
    {% else %}
    <div class="d-flex align-items-center me-3">Hello,<a href="{% url 'user_detail' user.pk %}"> {{ user.username }}</a>!</div>
    <a class="btn btn-outline-danger btn-sm" aria-current="page" href="{% url 'logout' %}?next={{ request.get_full_path }}">Logout</a>
    {% endif %}
    </div>
  </div>
</nav>

source/templates/partials/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination">
        <!-- First page -->
        <li class="page-item">
            <a href="?page=1" class="page-link">First</a>
        </li>

        <!-- Previous page -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
        {% endif %}

        <!-- List of pages -->
        {% for page in page_obj.paginator.page_range %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
            </li>
        {% endfor %}

        <!-- Next page -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        {% endif %}

        <!-- Last page -->
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                Last
            </a>
        </li>
    </ul>
</nav>

source/templates/partials/task_list.html
{% if is_paginated %}
    {% include 'partials/pagination.html' %}
{% endif %}

{% for task in task %}

    <div class="card mt-3">
          <div class="card-header">
  <a href="#" class="list-group-item list-group-item-action">
    Tasks for -{% for author in task.author.all %} {{ author.username }}{% endfor %}
  </a>
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ task.title }}</h5>
            <p class="card-text">{{ task.description }}</p>
            <a href="{% url 'task_detail' task.id %}" class="btn btn-primary">More</a>
          </div>
    </div>

{% endfor %}

source/templates/partials/user_forms.html
{% if not fields_only %}
    <form    action="{{ action_url }}"
    method="{{ form_method }}"
    enctype="multipart/form-data"
    class="w-50">
        {% csrf_token %}
{% endif %}
        {% for error in form.non_field_errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}

        {% for field in form %}
            <div class="input-group mb-3">
                <span class="input-group-text">{{ field.label }}</span>
                {{ field }}

                {% for error in field.errors %}
                    <p class="text-danger">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}

{% if not fields_only %}
        <button type="submit" class="btn btn-primary">{{ button_text|default:"Submit" }}</button>
    </form>
{% endif %}