source/projects/urls.py
from django.urls import path
from .views import ProjectsListView, ProjectDetailView, \
    ProjectUpdateView, ProjectDeleteView, ProjectCreateView, ProjectUserUpdateView, error_page

urlpatterns = [
    path('list/', ProjectsListView.as_view(), name='projects_list'),
    path('detail/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('update/<int:pk>/', ProjectUpdateView.as_view(), name='project_update'),
    path('update/users/<int:pk>/', ProjectUserUpdateView.as_view(), name='project_user_update'),
    path('delete/<int:pk>/', ProjectDeleteView.as_view(), name='project_delete'),
    path('create/', ProjectCreateView.as_view(), name='project_create'),
    path('error/', error_page, name='error_page'),

]

source/source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('accounts/', include('accounts.urls')),
    path('projects/', include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/tasks/urls.py
from django.urls import path
from .views import HomeView, TaskListView, TaskDetailView, TaskUpdateView, TaskDeleteView, TaskCreateView, MyTaskList

urlpatterns = [
    path('', HomeView.as_view(), name='home_page'),
    path('list/', TaskListView.as_view(), name='task_list'),
    path('mylist/', MyTaskList.as_view(), name='my_task_list'),
    path('detail/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('update/<int:pk>/', TaskUpdateView.as_view(), name='task_update'),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name='task_delete'),
    path('create/', TaskCreateView.as_view(), name='create_task'),

]

source/projects/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.

class Projects(models.Model):
    name = models.CharField(max_length=250, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(get_user_model(), related_name='users', verbose_name='users')

    def __str__(self):
        return self.name

    def to_dict(self):
        return {
            'title': self.name,
            'description': self.description,
            'created_at': self.created_at.isoformat(),
        }

source/tasks/models.py
from django.contrib.auth import get_user_model
from django.db import models
from projects.models import Projects


class Task(models.Model):
    STATUS_CHOICES = [
        ('in progress', 'In progress'),
        ('done', 'Done'),
        ('is waiting', 'Is waiting'),
    ]

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='in progress')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ManyToManyField(get_user_model(), related_name='tasks', verbose_name='Author')
    project = models.ForeignKey(Projects, on_delete=models.CASCADE, related_name='tasks')

    def __str__(self):
        return self.title

    def to_dict(self):
        return {
            'title': self.title,
            'description': self.description,
            'status': self.status,
            'project': self.project,
            'created_at': self.created_at.isoformat(),
        }

source/projects/forms.py
from django import forms
from .models import Projects
from django.contrib.auth import get_user_model


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Projects
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)


class ProjectUserEditForm(ProjectForm):
    class Meta(ProjectForm.Meta):
        # model = Projects
        fields = ['users']
        widgets = {'users': forms.SelectMultiple(attrs={'class': 'form-select'})}

source/projects/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.models import Permission
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from .models import Projects
from django.db.models import Q
from .forms import ProjectForm, ProjectUserEditForm
from django.contrib.auth.models import Group
from django.shortcuts import redirect
from django.contrib import messages


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Projects
    form_class = ProjectForm
    template_name = 'projects/project_create.html'
    success_url = reverse_lazy('projects_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        form.instance.save()
        form.instance.users.add(self.request.user)
        return super().form_valid(form)


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    model = Projects
    template_name = 'projects/project_confirm_delete.html'
    success_url = reverse_lazy('projects_list')
    context_object_name = 'project'
    permission_required = 'projects.delete_projects'

    def has_permission(self):
        # Получаем текущий проект
        project = self.get_object()
        # Получаем текущего пользователя
        user = self.request.user
        # Проверяем, есть ли пользователь в списке участников проекта
        return user in project.users.all()


class ProjectUpdateView(PermissionRequiredMixin, UpdateView):
    model = Projects
    template_name = 'projects/project_update.html'
    success_url = reverse_lazy('projects_list')
    form_class = ProjectForm
    permission_required = 'projects.change_projects'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def has_permission(self):
        # Получаем текущий проект
        project = self.get_object()
        # Получаем текущего пользователя
        user = self.request.user
        # Проверяем, есть ли пользователь в списке участников проекта
        return user in project.users.all()


def error_page(request):
    return render(request, 'partials/error_page.html')


class ProjectUserUpdateView(PermissionRequiredMixin, UpdateView):
    model = Projects
    template_name = 'projects/project_update.html'
    success_url = reverse_lazy('projects_list')
    form_class = ProjectUserEditForm
    permission_required = 'projects.change_users_projects'

    def has_permission(self):
        # Получаем текущий проект
        project = self.get_object()
        # Получаем текущего пользователя
        user = self.request.user
        # Проверяем, есть ли пользователь в списке участников проекта
        if user in project.users.all():
            return True
        else:
            # Если пользователь не в списке участников проекта, добавляем сообщение об ошибке
            messages.error(self.request, 'Access denied: You are not a member of this project.')
            return False

    def handle_no_permission(self):
        # Если у пользователя нет разрешения, перенаправляем его на страницу ошибки
        return redirect('error_page')


    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class ProjectDetailView(PermissionRequiredMixin, DetailView):
    model = Projects
    template_name = 'projects/project_detail.html'
    context_object_name = 'project'
    success_url = reverse_lazy('projects_list')
    permission_required = 'projects.view_projects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = self.object.tasks.all()
        return context


class ProjectsListView(ListView):
    model = Projects
    template_name = 'projects/projects_list.html'
    context_object_name = 'projects'
    paginate_by = 5
    paginate_orphans = 0

    def get_queryset(self):
        queryset = super().get_queryset()

        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(Q(title__icontains=search_query))

        sort_by = self.request.GET.get('sort_by')
        if sort_by:
            queryset = queryset.order_by(sort_by)
        return queryset

# Create your views here.

source/templates/projects/project_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
  <div class="card-header">
    Подтверждение удаления project
  </div>
  <div class="card-body">
    <h5 class="card-title">Вы уверены, что хотите удалить project "{{ project.name }}"?</h5>
    <p class="card-text">{{ project.description }}</p>
    <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger m-2">Удалить</button><a href="{% url 'projects_list' %}" class="btn btn-primary" >Отмена</a>
  </form>

  </div>
</div>
{% endblock %}

source/templates/projects/project_create.html
{% extends 'base.html' %}


{% block content %}
  <h2>Create Project</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Create Project</button>

  </form>
{% endblock %}

source/templates/projects/project_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card m-3">
        <div class="card-header">
            <a href="#" class="list-group-item list-group-item-action">
                Detail - Project
            </a>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ project.name }}</h5>
            <p class="card-text">{{ project.description }}</p>
            <p class="card-text">Project for - {% for user in project.users.all %} {{ user.username }} {% endfor %}</p>

            <p class="card-text">created at: {{ project.created_at }}</p>
            {% if perms.projects.change_projects and request.user in project.users.all %}
                <a href="{% url 'project_update' project.id %}" class="btn btn-primary">Edit</a>

            {% else %}
                <button class="btn btn-primary" disabled>Edit</button>
                {% if perms.projects.change_users_projects %}
                    <a href="{% url 'project_user_update' project.id %}" class="btn btn-primary">User Edit</a>
                    {% endif %}
            {% endif %}
            {% if perms.projects.delete_projects and request.user in project.users.all %}
                <a href="{% url 'project_delete' project.pk %}" class="btn btn-danger">Delete</a>
            {% else %}
                <button class="btn btn-danger" disabled>Delete</button>
            {% endif %}
        </div>
    </div>

    <h5 class="m-3">Project task</h5>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for task in tasks %}
            <div class="col">
                <div class="card">
                    <div class="card-header"><h5 class="card-title">{{ task.title }}</h5></div>
                    <div class="card-body">

                        <p class="card-text">description - {{ task.description }}</p>
                        <p class="card-text">status - {{ task.status }}</p>
                        <p class="card-text">Tasks for - {% for author in task.author.all %}
                            {{ author.username }} {% endfor %}</p>
                        <p class="card-text">created at: {{ task.created_at }}</p>
                    </div>
                <div class="m-1">
                    {% if perms.tasks.change_task and request.user in task.author.all %}
                        <a href="{% url 'task_update' task.id %}" class="btn btn-primary">Edit</a>
                    {% else %}
                        <button class="btn btn-primary" disabled>Edit</button>
                    {% endif %}
                    {% if perms.tasks.delete_task and request.user in task.author.all %}
                        <a href="{% url 'task_delete' task.pk %}" class="btn btn-danger">Delete</a>
                    {% else %}
                        <button class="btn btn-danger" disabled>Delete</button>
                    {% endif %}
                </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

source/templates/projects/project_update.html
{% extends 'base.html' %}

{% block content %}
  <h2>Edit project</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock %}

source/templates/projects/projects_list.html
{% extends 'base.html' %}

{% block content %}
<div >
    {% if perms.projects.add_projects  %}
        <h2>Projects List <a href="{% url 'project_create' %}" class="btn btn-success m-3">Add New Project</a></h2>
    {% else %}
        <h2>Projects List</h2>
    {% endif %}


</div>

<div class="w-25 mb-3">
  <form method="get" class="d-flex align-items-center" action="{% url 'task_list' %}">
    <input type="text" name="search" placeholder="Search by title" class="form-select form-select-sm me-1">
    <button type="submit" class="btn btn-outline-dark btn-sm">Search</button>
  </form>
</div>

<div class="w-25 mb-3">
    <form method="GET" class="d-flex align-items-center">
        <select name="sort_by" class="form-select form-select-sm me-1" id="sort_by">
                <option value="" selected disabled>Select</option>
                <option value="id">ID</option>
                <option value="name">name</option>
        </select>
                <button type="submit" class="btn btn-outline-dark btn-sm">Sort</button>
    </form>
</div>

    {% include 'partials/pagination.html' %}
{% for projects in object_list %}
    <div class="card m-3">
          <div class="card-header">

  <a href="#" class="list-group-item list-group-item-action">
    Project for -{% for user in projects.users.all %} {{ user.username }}{% endfor %}</a>

          </div>
          <div class="card-body">
            <h5 class="card-title">{{ projects.name }}</h5>
            <p class="card-text">{{ projects.description }}</p>
            <a href="{% url 'project_detail' projects.id %}" class="btn btn-primary">More</a>
          </div>
    </div>
{% endfor %}
    {% include 'partials/pagination.html' %}
{% endblock %}