source/source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('accounts/', include('accounts.urls')),
    path('projects/', include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/tasks/urls.py
from django.urls import path
from .views import HomeView, TaskListView, TaskDetailView, TaskUpdateView, TaskDeleteView, TaskCreateView, MyTaskList

urlpatterns = [
    path('', HomeView.as_view(), name='home_page'),
    path('list/', TaskListView.as_view(), name='task_list'),
    path('mylist/', MyTaskList.as_view(), name='my_task_list'),
    path('detail/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('update/<int:pk>/', TaskUpdateView.as_view(), name='task_update'),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name='task_delete'),
    path('create/', TaskCreateView.as_view(), name='create_task'),

]

source/tasks/models.py
from django.contrib.auth import get_user_model
from django.db import models
from projects.models import Projects


class Task(models.Model):
    STATUS_CHOICES = [
        ('in progress', 'In progress'),
        ('done', 'Done'),
        ('is waiting', 'Is waiting'),
    ]

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='in progress')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ManyToManyField(get_user_model(), related_name='tasks', verbose_name='Author')
    project = models.ForeignKey(Projects, on_delete=models.CASCADE, related_name='tasks')

    def __str__(self):
        return self.title

    def to_dict(self):
        return {
            'title': self.title,
            'description': self.description,
            'status': self.status,
            'project': self.project,
            'created_at': self.created_at.isoformat(),
        }

source/tasks/forms.py
from django import forms
from .models import Task
from django.contrib.auth import get_user_model


class TaskForm(forms.ModelForm):
    author = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-select'}),
        required=False
    )

    class Meta:
        model = Task
        fields = ['title', 'description', 'status', 'author', 'project']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'project': forms.Select(attrs={'class': 'form-select'})
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
            if not self.cleaned_data.get('author'):
                instance.author.add(self.user)
            else:
                instance.author.set(self.cleaned_data.get('author'))
        return instance

source/tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, DeleteView, CreateView
from django.http import JsonResponse
from projects.models import Projects
from .models import Task
from django.urls import reverse_lazy
from .forms import TaskForm


class HomeView(TemplateView):
    template_name = 'home_page.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'home_page.html')


class TaskListView(ListView):
    model = Task
    template_name = 'tasks/task_list.html'
    context_object_name = 'tasks'
    paginate_by = 5
    paginate_orphans = 0

    def get_queryset(self):
        queryset = super().get_queryset()

        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(Q(title__icontains=search_query))

        sort_by = self.request.GET.get('sort_by')
        if sort_by:
            queryset = queryset.order_by(sort_by)
        return queryset


class MyTaskList(TaskListView):
    template_name = 'tasks/my_task_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_tasks'] = Task.objects.filter(author=self.request.user)
        return context


class TaskDetailView(DetailView):
    model = Task
    template_name = 'tasks/task_detail.html'
    context_object_name = 'task'


class TaskUpdateView(PermissionRequiredMixin, UpdateView):
    model = Task
    template_name = 'tasks/task_update.html'
    # fields = ['title', 'description', 'status']
    success_url = reverse_lazy('task_list')
    form_class = TaskForm
    permission_required = 'tasks.change_task'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def has_permission(self):
        task = self.get_object()
        user = self.request.user

        return user in task.project.users.all()


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    model = Task
    template_name = 'tasks/task_confirm_delete.html'
    success_url = reverse_lazy('task_list')
    context_object_name = 'task'
    permission_required = 'tasks.delete_task'

    def has_permission(self):
        task = self.get_object()
        user = self.request.user

        return user in task.project.users.all()


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/create_task.html'
    success_url = reverse_lazy('task_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        form.instance.save()
        form.instance.author.add(self.request.user)
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        project = request.POST.get('project')
        if project:
            project_instance = Projects.objects.get(id=project)
            if request.user not in project_instance.users.all():
                # raise PermissionDenied("You do not have permission to create an issue in this project.")
                return JsonResponse({'error': "You do not have permission to create an issue in this project."},
                                    status=403)
        return super().dispatch(request, *args, **kwargs)

source/templates/tasks/create_task.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h2>Create Task</h2>
  <form id="task-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Create Task</button>

  </form>
       {% include 'partials/error_modal.html' %}
    {% block js %}
<script>
$("#task-form").submit(function(event) {
    event.preventDefault();

    $.ajax({
        type: "POST",
        url: "{% url 'create_task' %}",
        data: $(this).serialize(),
        success: function(response) {
            window.location.href = "{% url 'task_list' %}";
        },
        error: function(response) {
            if(response.status === 403) {
                $('#errorModalBody').text(response.responseJSON.error);
                $('#errorModal').modal('show');
            }
        }
    });
});
    </script>
        {% endblock %}
{% endblock %}

source/templates/tasks/my_task_list.html
{% extends 'base.html' %}

{% block content %}

  <h2>My Task List</h2>

{% for task in user_tasks %}

    <div class="card mt-3">
          <div class="card-header">
  <a href="#" class="list-group-item list-group-item-action">
    Tasks for -{% for author in task.author.all %} {{ author.username }}{% endfor %}
  </a>
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ task.title }}</h5>
            <p class="card-text">{{ task.description }}</p>
            <a href="{% url 'task_detail' task.id %}" class="btn btn-primary">More</a>
          </div>
    </div>

{% endfor %}

{% endblock %}

source/templates/tasks/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
  <div class="card-header">
    Подтверждение удаления задачи
  </div>
  <div class="card-body">
    <h5 class="card-title">Вы уверены, что хотите удалить задачу "{{ task.title }}"?</h5>
    <p class="card-text">{{ task.description }}</p>
    <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger m-2">Удалить</button><a href="{% url 'task_list' %}" class="btn btn-primary" >Отмена</a>
  </form>

  </div>
</div>
{% endblock %}

source/templates/tasks/task_detail.html
{% extends 'base.html' %}

{% block content %}
        <div class="card mt-3">
          <div class="card-header">
  <a href="#" class="list-group-item list-group-item-action">
    Detail - Task
  </a>
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ task.title }}</h5>
            <p class="card-text">{{ task.description }}</p>
            <p class="card-text">Status - {{ task.status }}</p>
            <p class="card-text">Project - {{ task.project }}</p>

            <p class="card-text">Tasks for - {% for author in task.author.all %} {{ author.username }} {% endfor %}</p>

              <p class="card-text">created at: {{ task.created_at }}</p>
              {% if perms.tasks.change_task and request.user in task.author.all %}
            <a href="{% url 'task_update' task.id %}" class="btn btn-primary">Edit</a>
    {% else %}
    <button class="btn btn-primary" disabled>Edit</button>
              {% endif %}
          {% if perms.tasks.delete_task and request.user in task.author.all%}
            <a href="{% url 'task_delete' task.pk %}" class="btn btn-danger">Delete</a>
              {% else %}
    <button class="btn btn-danger" disabled>Delete</button>
              {% endif %}
          </div>
    </div>

{% endblock %}

source/templates/tasks/task_list.html
{% extends 'base.html' %}

{% block content %}

    <div>
    {% if perms.tasks.add_task  %}
  <h2>Task List <a href="{% url 'create_task' %}" class="btn btn-success m-3">Add New Task</a></h2>
        {% else %}
        <h2>Task List</h2>
    {% endif %}
</div>
<div class="w-25 mb-3">
  <form method="get" class="d-flex align-items-center" action="{% url 'task_list' %}">
    <input type="text" name="search" placeholder="Search by title" class="form-select form-select-sm me-1">
    <button type="submit" class="btn btn-outline-dark btn-sm">Search</button>
  </form>
</div>

<div class="w-25 mb-3">
    <form method="GET" class="d-flex align-items-center">
        <select name="sort_by" class="form-select form-select-sm me-1" id="sort_by">
                <option value="" selected disabled>Select</option>
                <option value="id">ID</option>
                <option value="title">title</option>
                <option value="status">status</option>
        </select>
                <button type="submit" class="btn btn-outline-dark btn-sm">Sort</button>
    </form>
</div>

    {% include 'partials/pagination.html' %}
{% for task in object_list %}
    <div class="card mt-3">
          <div class="card-header">

  <a href="#" class="list-group-item list-group-item-action">
    Tasks for -{% for author in task.author.all %} {{ author.username }}{% endfor %}</a>

          </div>
          <div class="card-body">
            <h5 class="card-title">{{ task.title }}</h5>
            <p class="card-text">{{ task.description }}</p>
            <a href="{% url 'task_detail' task.id %}" class="btn btn-primary">More</a>
          </div>
    </div>
{% endfor %}
    {% include 'partials/pagination.html' %}
{% endblock %}

source/templates/tasks/task_update.html
{% extends 'base.html' %}

{% block content %}
  <h2>Edit task</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock %}